<!-- Navbar.vue -->
<template>

  <div>
    <br/>
  
    <h1 class="text-center">
      <a class="navbar-brand" href="#">
      <img :src="paper" width="70" height="70" class="d-inline-block align-center" alt="">
      News Benchmark
    </a>
    </h1>

    <br/>

    <div class="p-container">
      <p class="paragraph">This study presents NewsBench, a novel benchmak framework developed to evaluate the capabiity of Large Lanquage Models (lMs)in Chinese jouralisticWriting Proficiency (JWP) and their Safety Adherence (SA), addressing the gap between journalistic ethics and the risks associated with Al utilization. Comprising1.267 tasks across 5 editoral applications, 7 aspects (incuding safety and iouralisic wrting with 4 detaled facets), and spanning 24 news topics domains,NewsBench emplys wo GPT-4 based automalic evalualion proiocols validated by buman assessment Our comprehensive anawsis of 41 ulMs highightedGPT-4 and ERNlE Bot as top performers, yet revealed a relative deficiency in joumalisic ethic adherence duing creative wrting tasks. These findings underscorthe need for enhanced ethical quidance in Al-generated joumalisic content, marking a step fonward in aigning Al capablies with jouralistic standards andsafety considerations.</p>
    </div>

    <br/>

    <div>
      <img :src="newsbench_architecture" style="width: 350px; height: 350px;" class="rounded mx-auto d-block" alt="...">
      <figcaption class="figure-caption" style="margin: 0 auto; width: 45%;">Figure 1: The key components and processes of the NewsBench benchmark. The numbers inside the brackets indicate the task counts for the subsets. The bold border boxes are the output scores</figcaption>
    </div>

    <br/>

    <div  class="p-container">
      <p class="paragraph">The benchmark is designed to evaluate two principal criteria: <b>Journalistic Writing Proficiency (JWP)</b> and <b>Safety Adherence (SA)</b> in content generated by LLMs. In alignment with benchmark design methodologies referenced in existing literature, our framework also incorporates both open-ended generation tasks and multiple-choice tasks. Consequently, we have constructed 4 subsets with a total of 1267 tasks - <b>JWP generation</b> tasks,<b>JWP multiple choice</b> tasks,<b>SA generation</b> tasks and <b>SA multiple choice</b> tasks. In addition, each subset covers 5 common journalistic editorial applications and up to 24 domains.</p>
    </div>

    <br/>

    <div  class="p-container">
      <p class="paragraph">Figure 1 illustrates the comprehensive design of the NewsBench evaluation framework. This framework inputs tasks from four distinct subsets into a targeted Large Language Model (LLM) to elicit corresponding multiple-choice answers and generated textual responses. </p>
    </div>

    <br/>

    <div  class="p-container">
      <p class="paragraph">The benchmark framework utilizes the tasks it has constructed to automate the reference-free evaluation of large language models (LLMs), focusing on their proficiency in general journalistic writing and their adherence to safety standards. While the evaluation of multiple-choice questions can be straightforwardly conducted by calculating accuracy, assessing generated content necessitates a more complicated approach. Drawing on recent advancements in natural language generation evaluation methodologies, which have employed LLMs for the automated assessment of highly specific attributes, we have developed two distinctive automatic evaluation protocols. These protocols are designed to assess general journalistic writing proficiency and safety standard compliance, respectively, using GPT-4. Additionally, we've performed human validation to ensure the effectiveness of our evaluation framework and its alignment with human judgment.</p>
    </div>

    <br/>

    <hr style="width: 60%;margin: 0 auto;"/>

    <h3 class="text-center">
      Result
    </h3>

    <div  class="p-container">
      <p class="paragraph">You can view more detailed evaluation protocol details and grading results in 
        <a href="https://www.iaar.ac.cn/">Paper</a>
         and 
         <b>Leaderboard.</b></p>
    </div>


    <footer>
      &copy; 2024 <a href="https://www.iaar.ac.cn/" style="color: black;">IAAR</a> All Rights Reserved.
    </footer>
    
  </div>

</template>

<script>
export default {
  name: 'MyHome',
  data(){
    return {
      paper: require('../assets/paper.png'),
      newsbench_architecture: require('../assets/newsbench_architecture1.png')
    }
  }
}
</script>

<style>
  h1 {
    text-align: center;
    margin-top: 50px;
    font-weight: bold;
  }

  .paragraph {
    text-align: justify;
    margin-top: 30px; /* 与h3保持一段距离 */
    margin-left: 100px;
    margin-right: 100px;
  }

  footer {
    text-align: center;
    margin-top: 100px;
  }

  .p-container {
  width: 70%; /* 表格容器占据页面宽度的70% */
  margin: 0 auto; /* 居中显示 */
  }

</style>
